
name: Go

on:
  push:
    paths:
      - internal/server/**/*
      - .github/workflows/internal_server.yml
    branches:
      - main
      - staging
  pull_request:
    paths:
      - internal/server/**/*
      - .github/workflows/internal_server.yml


workspace: internal/server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      # run: go test -v ./...
      run: echo ok